version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: panda-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - panda-network
    restart: unless-stopped

networks:
  panda-network:
    driver: bridge

volumes:
  node_modules:
  next_cache: